apiVersion: v1
kind: Secret
metadata:
  name: memberlist
  namespace: metallb-system
stringData:
  secretkey: "2jONxeufdsiNuJQXtsoVSqc8wCjdk808+k9DDl/bgqih1PHYByu+ORbpy+sdNrQc\n8ooU6AWz2Kw1MqF52cEbc+HiUBVYjsfTsqoQLlAFgRXcaX6LC3KpEhB2+fNIXMaz\nIoslTou4onntRzJlXjy45OiNdw4G53MI4jjm1+y4PSI="
